name: Publish to PyPI.org
on:
  release:
    types: [published]
jobs:
  pypi:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Tag Check
        run: |
          sed -En '/\[tool.poetry\]/,/^version/{ s/^version *= *"(.+)"/\1/p; }' pyproject.toml | read toml_version
          cat <<-EOF
            GITHUB_REF_TYPE: $GITHUB_REF_TYPE
            GITHUB_REF_NAME: $GITHUB_REF_NAME
            pyproject.toml[tool.poetry.version]: $toml_version
          EOF
          function bail() { echo "Error: pyproject.toml 'version' and git release tag must match"; exit 1; }
          [[ "${GITHUB_REF_TYPE}" == 'tag' ]] || bail
          [[ "${GITHUB_REF_NAME}" == "${toml_version}" ]] || bail
      - run: python3 -m pip install --upgrade build && python3 -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
